file:
  log_dir: 'log\\'
dataset:
  threshold: 0
  dataset_size: max
  att_lstm_num: 3
  long_term_lstm_seq_len: 3
  short_term_lstm_seq_len: 7
  nbhd_size: 2
  cnn_nbhd_size: 3
model:
  lstm_seq_len: 7
  num_choice: 3
  num_layers: 3
  device: 'cuda'
training:
  epoch_max: 100
  learning_rate: 0.025
  momentum: 0.9
  weight_decay: 3e-4
  batch_size: 64
  num_workers: 0
  train_portion: 0.8